---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Check if homebrew is installed
      ansible.builtin.shell: which brew
      register: brew_check
    - name: Install homebrew if not found in system
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_check.stdout.find('not found') != -1
    - name: Install latest Oh My Posh
      ansible.builtin.shell: brew install jandedobbeleer/oh-my-posh/oh-my-posh
    - name: Install Ruby with Homebrew
      ansible.builtin.shell: brew install ruby
    - name: Install ColorLS
      ansible.builtin.shell: gem install colorls
      become: true
    - name: Install Pyenv
      ansible.builtin.shell: brew update && brew install pyenv
    - name: Install ZSH AutoSuggestions
      ansible.builtin.shell: brew install zsh-autosuggestions
    - name: Install FZF(FuzzyFinder)
      ansible.builtin.shell: brew install fzf
    - name: Check if ZSH Autocomplete already clone
      stat:
        path: "~/zsh-autocomplete"
      register: zsh_autocomplete_folder_present
    - name: Warn of ZSH Autocomplete present
      debug:
        msg: ZSH Autocomplete folder dir exists
      when: zsh_autocomplete_folder_present.stat.exists
    - name: Pull down ZSH Autocomplete
      ansible.builtin.shell: git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git ~/zsh-autocomplete
      when: not zsh_autocomplete_folder_present.stat.exists
    - name: Install FiraCode Nerd font
      ansible.builtin.copy:
        src: FiraCodeNerdFontMono-Medium.ttf
        dest: ~/Library/Fonts/FiraCodeNerdFontMono-Medium.ttf