- name: Clear all items from the dock
  ansible.builtin.shell: defaults write "com.apple.dock" "persistent-apps" -array; killall Dock

- name: Check if HTOP is installed
  ansible.builtin.shell: which htop
  register: check_htop
  failed_when: check_htop.rc >= 2

- name: Install bat
  ansible.builtin.shell: brew install top
  when: check_htop.rc != 0

- name: Check if BPYTOP is installed
  ansible.builtin.shell: which bpytop
  register: check_bpytop
  failed_when: check_bpytop.rc >= 2
  
- name: Install bat
  ansible.builtin.shell: brew install bpytop
  when: check_bpytop.rc != 0