- name: Check if slack is installed
  ansible.builtin.shell: brew list slack
  register: check_slack
  failed_when: check_slack.rc >= 2
- name: Install slack if not found in system
  ansible.builtin.shell: brew install --cask slack
  when: check_slack.rc != 0

- name: Check if iterm2 is installed
  ansible.builtin.shell: brew list iterm2
  register: check_iterm2
  failed_when: check_iterm2.rc >= 2
- name: Install iterm2 if not found in system
  ansible.builtin.shell: brew install --cask iterm2
  when: check_iterm2.rc != 0

- name: Check if VS Code is installed
  ansible.builtin.shell: brew list visual-studio-code
  register: check_vscode
  failed_when: check_vscode.rc >= 2
- name: Install VS Code if not found in system
  ansible.builtin.shell: brew install visual-studio-code
  when: check_vscode.rc != 0

- name: Check if MacPass is installed
  ansible.builtin.shell: brew list macpass
  register: check_macpass
  failed_when: check_macpass.rc >= 2
- name: Install MacPass if not found in system
  ansible.builtin.shell: brew install --cask macpass
  when: check_macpass.rc != 0

- name: Check if Postman is installed
  ansible.builtin.shell: brew list postman
  register: check_postman
  failed_when: check_postman.rc >= 2
- name: Install Postman if not found in system
  ansible.builtin.shell: brew install --cask postman
  when: check_postman.rc != 0
