- name: Check if slack is installed
  ansible.builtin.shell: brew list slack
  register: check_slack
  failed_when: check_slack.rc >= 2
- name: Install slack if not found in system
  ansible.builtin.shell: brew install --cask slack
  when: check_slack.rc != 0

- name: Check if iterm2 is installed
  ansible.builtin.shell: brew list iterm2
  register: check_iterm2
  failed_when: check_iterm2.rc >= 2
- name: Install iterm2 if not found in system
  ansible.builtin.shell: brew install --cask iterm2
  when: check_iterm2.rc != 0 and install_iterm2

- name: Check if VS Code is installed
  ansible.builtin.shell: brew list visual-studio-code
  register: check_vscode
  failed_when: check_vscode.rc >= 2
- name: Install VS Code if not found in system
  ansible.builtin.shell: brew install visual-studio-code
  when: check_vscode.rc != 0

- name: Check if MacPass is installed
  ansible.builtin.shell: brew list macpass
  register: check_macpass
  failed_when: check_macpass.rc >= 2
- name: Install MacPass if not found in system
  ansible.builtin.shell: brew install --cask macpass
  when: check_macpass.rc != 0

- name: Check if Postman is installed
  ansible.builtin.shell: brew list postman
  register: check_postman
  failed_when: check_postman.rc >= 2
- name: Install Postman if not found in system
  ansible.builtin.shell: brew install --cask postman
  when: check_postman.rc != 0

- name: Check if Firefox is installed
  ansible.builtin.shell: brew list firefox
  register: check_firefox
  failed_when: check_firefox.rc >= 2
- name: Install Firefox if not found in system
  ansible.builtin.shell: brew install --cask firefox
  when: check_firefox.rc != 0 and install_firefox

- name: Check if Chrome is installed
  ansible.builtin.shell: brew list google-chrome
  register: check_chrome
  failed_when: check_chrome.rc >= 2
- name: Install Chrome if not found in system
  ansible.builtin.shell: brew install --cask google-chrome
  when: check_chrome.rc != 0 and install_chrome

- name: Check if Discord is installed
  ansible.builtin.shell: brew list discord
  register: check_discord
  failed_when: check_discord.rc >= 2
- name: Install Discord if not found in system
  ansible.builtin.shell: brew install --cask discord
  when: check_discord.rc != 0 and install_discord

- name: Check if Rectangle is installed
  ansible.builtin.shell: brew list rectangle
  register: check_rectangle
  failed_when: check_rectangle.rc >= 2
- name: Install Rectangle if not found in system
  ansible.builtin.shell: brew install --cask rectangle
  when: check_rectangle.rc != 0 and install_rectangle

- name: Check if Maccy is installed
  ansible.builtin.shell: brew list maccy
  register: check_maccy
  failed_when: check_maccy.rc >= 2
- name: Install Maccy if not found in system
  ansible.builtin.shell: brew install --cask maccy
  when: check_maccy.rc != 0 and install_maccy

- name: Check if Ghostty is installed
  ansible.builtin.shell: brew list ghostty
  register: check_ghostty
  failed_when: check_ghostty.rc >= 2
- name: Install Ghostty if not found in system
  ansible.builtin.shell: brew install --cask ghostty
  when: check_ghostty.rc != 0 and install_ghostty

- name: Check if Windows App is installed
  ansible.builtin.shell: brew list windows-app
  register: check_windows_app
  failed_when: check_windows_app.rc >= 2
- name: Install Windows App if not found in system
  ansible.builtin.shell: brew install --cask windows-app  
  when: check_windows_app.rc != 0 and install_windows_app

- name: Check if LM Studio is installed
  ansible.builtin.shell: brew list lm-studio
  register: check_lm_studio
  failed_when: check_lm_studio.rc >= 2
- name: Install LM Studio if not found in system
  ansible.builtin.shell: brew install --cask lm-studio 
  when: check_lm_studio.rc != 0 and install_lm_studio


  