# - name: Check if TLDR is installed
#   ansible.builtin.shell: which tldr
#   register: tldr_check
#   ignore_errors: true
- name: Install latest TLDR
  ansible.builtin.shell: brew install tldr
  # when: tldr_check.stdout.find('not found') != -1

