- name: Check if FuzzyFinder is installed
  ansible.builtin.shell: which fzf
  register: check_fzf
  failed_when: check_fzf.rc >= 2
- name: Install FZF(FuzzyFinder)
  ansible.builtin.shell: brew install fzf
  when: check_fzf.rc != 0
