- name: Check if pyenv installed
  ansible.builtin.shell: which pyenv
  register: pyenv_check
  failed_when: pyenv_check.rc >= 2
- name: Install Pyenv
  ansible.builtin.shell: brew update && brew install pyenv
  when: pyenv_check.rc != 0
- name: Check if pyenv virtualenv installed
  ansible.builtin.shell: which pyenv-virtualenv
  register: pyenv_virtenv_check
  failed_when: pyenv_virtenv_check.rc >= 2
- name: Install Pyenv Virtualenv
  ansible.builtin.shell: brew install pyenv-virtualenv
  when: pyenv_virtenv_check != 0
