- name: Check if NVM is installed
  ansible.builtin.shell: brew list nvm
  register: check_nvm
  failed_when: check_nvm.rc >= 2
- name: Install NVM
  ansible.builtin.shell: brew install nvm
  when: check_nvm.rc != 0 and install_nvm

- name: Check if pyenv installed
  ansible.builtin.shell: brew list pyenv
  register: pyenv_check
  failed_when: pyenv_check.rc >= 2
- name: Install Pyenv
  ansible.builtin.shell: brew install pyenv
  when: pyenv_check.rc != 0 and install_pyenv

- name: Check if pyenv virtualenv installed
  ansible.builtin.shell: brew list  pyenv-virtualenv
  register: pyenv_virtenv_check
  failed_when: pyenv_virtenv_check.rc >= 2
- name: Install Pyenv Virtualenv
  ansible.builtin.shell: brew install pyenv-virtualenv
  when: pyenv_virtenv_check.rc != 0 and install_pyenv_virtualenv

- name: Check if UV installed
  ansible.builtin.shell: brew list uv
  register: uv_check
  failed_when: uv_check.rc >= 2
- name: Install UV
  ansible.builtin.shell: brew install uv
  when: uv_check.rc != 0 and install_uv

- name: Check if Docker Desktop installed
  ansible.builtin.shell: brew list docker
  register: docker_check
  failed_when: docker_check.rc >= 2
- name: Install Docker Desktop
  ansible.builtin.shell: brew install --cask docker
  when: docker_check.rc != 0 and install_docker