---
- name: Include install homebrew
  import_tasks: install_homebrew.yml
  when: install_homebrew
- name: Include install pyenv
  import_tasks: install_pyenv.yml
  when: install_pyenv
- name: Include install Oh My Posh
  import_tasks: install_oh_my_posh.yml
- name: Include install ZSH Addons
  import_tasks: install_zsh_addons.yml
- name: Include install ColorLS
  import_tasks: install_color_ls.yml
  when: install_colorls
- name: Include install FuzzyFinder
  import_tasks: install_fuzzy_finder.yml
- name: include install fonts
  import_tasks: install_fonts.yml
- name: include install tldr
  import_tasks: install_tldr.yml
- name: include install eza
  import_tasks: install_eza.yml
  when: install_eza
- name: include install bat
  import_tasks: install_bat.yml
  when: install_bat
- name: include install ripgrep
  import_tasks: install_ripgrep.yml
  when: install_ripgrep