---
- name: Mac Setup Base Playbook
  hosts: 127.0.0.1
  connection: local
  vars:
    install_desktop_apps: true
    install_terminal_apps: true
    install_developer_apps: true
    install_developer_fonts: true

    # Individual module controls

    # Desktop apps
    install_firefox: true
    install_chrome: true
    install_discord: true
    install_rectangle: true
    install_maccy: true
    install_ghostty: true
    install_iterm2: false
<<<<<<< HEAD
    install_raycast: true
=======
    install_windows_app: true
>>>>>>> 4fd682a2f65a9e2a6f3f3815c0f14d25ab15860c

    # Terminal apps
    install_awscli: true

    # Developer apps
    install_nvm: true
    install_uv: true
    install_docker: true
  roles:
    - setup_mac
