---
- name: Mac Setup Base Playbook
  hosts: 127.0.0.1
  connection: local
  vars:
    install_desktop_apps: true
    install_terminal_apps: true
    install_developer_apps: true
    install_developer_fonts: true
  roles:
    - setup_mac
