---
- name: Mac Setup Base Playbook
  hosts: 127.0.0.1
  connection: local
  vars:
    install_desktop_apps: true
    install_terminal_apps: true
    install_developer_apps: true
    install_developer_fonts: true

    # Individual module controls

    # Desktop apps
    install_firefox: true
    install_chrome: true
    install_discord: true
    install_rectangle: true
    install_maccy: true

    # Terminal apps
    install_awscli: true

    # Developer apps
    install_nvm: true
    install_pyenv: true
    install_pyenv_virtualenv: true # if pyenv is false, this should also be false
    install_uv: true
    install_docker: true
  roles:
    - setup_mac
